services:
  app:
    build:
      context: .
      dockerfile: .devcontainer/Dockerfile
    container_name: devcontainer_MainteLog
    volumes:
      - .:/workspace
    ports:
      - "8080:8080"
    depends_on:
      - db
    stdin_open: true
    tty: true
  db:
    image: mysql:8.0
    container_name: devcontainer_mysql
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
      MYSQL_DATABASE: ${MYSQL_DATABASE}
      MYSQL_USER: ${MYSQL_USER}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD}
    ports:
      - "3307:3306"
    volumes:
      - db-data:/var/lib/mysql
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql
volumes:
  db-data:
